Create sendinblue.lang
ATM-Consulting/dolibarr_module_sendinblue pull request #29
Opened 2021-12-14 21:22 UTC by glu000

Add German language file

2021-12-15 08:10 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +ATMAbout = Dieses Modul wurde entwickelt von <a href="http://www.atm-consulting.fr" target="_blank"> ATM Consulting </a> <br> Sie finden die Dokumentation auf unserer <a href = "http://wiki.atm-consu
```suggestion
ATMAbout = Dieses Modul wurde entwickelt von <a href="http://www.atm-consulting.fr" target="_blank"> ATM Consulting </a> <br> Sie finden die Dokumentation auf unserer <a href="http://wiki.atm-consulting.fr/index.php/Accueil" target="_ blank"> Wiki </a> <br> <br> Kontaktieren Sie uns bei technischen Fragen oder Feedback unter <a href="mailto:support@atm-consulting.fr"> support@atm-consulting.fr </a> <br> <br> Kontaktieren Sie uns bei kommerziellen Fragen unter <a href="mailto:contact@atm-consulting.fr"> contact@atm-consulting.fr </a> oder +33 9 77 19 50 70 <br> <br> Unsere anderen Module finden Sie auf <a href="http: //www.dolistore.com/search.php?orderby=position&orderway=desc&search_query=atm&Submit_search=Suche nach" target="_blank"> Dolistore </a>
```

2021-12-15 08:13 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueExplain = SendinBlue ist ein kostenloser E-Mail-Versanddienst <br> <u> <b> Internet erforderlich </b> </u> <br> Weitere Informationen finden Sie auf der <a href = "Website http://www.sendin
```suggestion
SendinBlueExplain = SendinBlue ist ein kostenloser E-Mail-Versanddienst <br> <u> <b> Internet erforderlich </b> </u> <br> Weitere Informationen finden Sie auf der <a href="Website http://www.sendinblue.com/" target="_blank"> SendinBlue </a>. <br> Um Ihre Anmeldedaten anzuzeigen: <a href="https://account.sendinblue.com/advanced/api" target="_blank "> Mein SendinBlue-Konto </a>
```

2021-12-15 08:16 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueDolibarrSettings = Die aktuelle Konfiguration (<a href="%s"> E-Mail-Konfiguration </a>) wird gespeichert, wenn diese Option aktiviert wird. <br> Um zur ursprünglichen Konfiguration zurückzu
> müssen Sie das Modul nur dadurch deaktivieren Taste

Problem hier?

2021-12-15 09:28 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SENDINBLUE_EXTRAFIELDS_SOCIETE_ALLOWEDHelp = Wählen Sie hier die zusätzlichen Attribute aus, die Sie synchronisieren möchten <br /> Damit dies korrekt funktioniert, müssen Sie diese / dieselben Attri
```suggestion
SENDINBLUE_EXTRAFIELDS_SOCIETE_ALLOWEDHelp = Wählen Sie hier die zusätzlichen Attribute aus, die Sie synchronisieren möchten <br /> Beachten Sie bitte, dass Sie im Abschnitt "Parameter > Kontakte und CRM-Attribute > Attributfelder" als Name der Sendinblue-Attribute den Code des entsprechenden Dolibarr-Zusatzfeld benutzen müssen.
```

2021-12-15 09:28 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SENDINBLUE_EXTRAFIELDS_CONTACT_ALLOWEDHelp = Wählen Sie hier die zusätzlichen Attribute aus, die Sie synchronisieren möchten <br /> Damit dies korrekt funktioniert, müssen Sie diese / dieselben Attri
```suggestion
SENDINBLUE_EXTRAFIELDS_CONTACT_ALLOWEDHelp = Wählen Sie hier die zusätzlichen Attribute aus, die Sie synchronisieren möchten <br /> Beachten Sie bitte, dass Sie im Abschnitt "Parameter > Kontakte und CRM-Attribute > Attributfelder" als Name der Sendinblue-Attribute den Code des entsprechenden Dolibarr-Zusatzfeld benutzen müssen.
```

2021-12-15 09:33 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueNewListName = Erstellen Sie die Liste auf SendinBlue (neu laden Sie diese Seite zum Aktualisieren)
```suggestion
SendinBlueNewListName = Erstellen Sie die Liste auf SendinBlue (laden Sie diese Seite erneut zum Aktualisieren)
```

2021-12-15 09:34 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueOr = Or
```suggestion
SendinBlueOr = Oder
```

2021-12-15 09:37 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueUpdateStatus = Aktualisieren Sie den Status von Dolibarr-Empfängern von SendinBlue
> Aktualisieren Sie

Ich bin mir nicht sicher, dass die Befehlsform hier geeignet ist.

2021-12-15 09:38 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueConfirmUpdateCampaignText = Dieser Vorgang kann sehr lang sein und zu einer Fehlermeldung führen, wenn die maximale Ausführungszeit überschritten wurde <br/> Bitten Sie Ihren Dolibarr-Admin
```suggestion
SendinBlueConfirmUpdateCampaignText = Dieser Vorgang kann sehr lang sein und zu einer Fehlermeldung führen, wenn die maximale Ausführungszeit überschritten wurde <br/> Bitten Sie Ihren Dolibarr-Administrator, diesen Task im Batch-Modus über die Befehlszeile auszuführen <br > <textarea cols="60" row="2" wrap="soft">php %s</textarea>;
```

2021-12-15 09:39 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendInBlueReturnError = Sendinblue hat den folgenden Fehler zurückgegeben:% s
```suggestion
SendInBlueReturnError = Sendinblue hat den folgenden Fehler zurückgegeben: %s
```

2021-12-15 09:43 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueExplainIndex = Um eine SendinBlue-Kampagne zu erstellen, müssen Sie eine Empfängerliste / ein Segment definieren. <br/> Um eine Liste zu erstellen, gehen Sie zu <a href = "http://www.sendin
```suggestion
SendinBlueExplainIndex = Um eine SendinBlue-Kampagne zu erstellen, müssen Sie eine Empfängerliste / ein Segment definieren. <br/> Um eine Liste zu erstellen, gehen Sie zu <a href="http://www.sendinblue.com/" target="_blank"> SendinBlue </a>. <br/> Sie finden einen Helfer auf der Registerkarte <b>%s </b> von <b>%s </b> oder nachdem Sie eine Dolibarr-E-Mail erstellt und Empfänger auf der Registerkarte SendinBlue angesteuert haben.
```

2021-12-15 09:44 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueConfirmUpdateAllCampaignText = Dieser Vorgang kann sehr lang sein und zu einer Fehlermeldung führen, wenn die maximale Ausführungszeit überschritten wurde <br/> Bitten Sie Ihren Dolibarr-Ad
```suggestion
SendinBlueConfirmUpdateAllCampaignText = Dieser Vorgang kann sehr lang sein und zu einer Fehlermeldung führen, wenn die maximale Ausführungszeit überschritten wurde <br/> Bitten Sie Ihren Dolibarr-Administrator, diese Aufgabe im Batch-Modus über die Befehlszeile zu starten <br><textarea cols="60" rows="2" wrap="soft">php %s</textarea>;
```

2021-12-15 09:44 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueConfirmCreateEmailingFromCampaign = Möchten Sie wirklich ein E-Mailing erstellen, das mit der Kampagne "% s" verknüpft ist?
```suggestion
SendinBlueConfirmCreateEmailingFromCampaign = Möchten Sie wirklich ein E-Mailing erstellen, das mit der Kampagne "%s" verknüpft ist?
```

2021-12-15 09:48 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueHardBounce = Hard Bounce
```suggestion
SendinBlueHardBounce = Hard-Bounce
```
Zur Einheitlichkeit mit "Soft-Bounce"

2021-12-15 09:48 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueOpen = Open
```suggestion
SendinBlueOpen = Öffnen
```

2021-12-15 09:51 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueImportCopyForm = Import von SendinBlue (beglaubigte Kopie)
```suggestion
SendinBlueImportCopyForm = Import von SendinBlue ()
```

2021-12-15 09:56 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueImportCopyForm = Import von SendinBlue (beglaubigte Kopie)
> beglaubigte Kopie

John sagt mir, dass mit "copie conforme" gemeint wird, dass die Kontakte komplett durch Dolibarr-Kontakte erstellt werden. Ich denke, hier sollte es ein anderes Adjektiv sein, z.B. "zurückgesetzt" (aber man könnte was besseres finden, ich bin leider kein Muttersprachler und habe Schwierigkeiten, das richtige Wort zu finden)

2021-12-15 09:58 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueExportCopyTo = Export nach SendinBlue (zertifizierte Kopie)
Gleich wie oben: "zertifiziert" scheint mir hier nicht geeignet.

2021-12-15 09:59 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueEmailNotSync = Die Empfänger der SendinBlue-Liste / des Segments unterscheiden sich von den in Dolibarr definierten. Verwenden Sie das Bedienfeld oben, um sie zu synchronisieren.
```suggestion
SendinBlueEmailNotSync = Die Empfänger der SendinBlue-Liste / des Segments unterscheiden sich von den in Dolibarr definierten Empfänger. Verwenden Sie das Bedienfeld oben, um sie zu synchronisieren.
```

2021-12-15 10:00 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +SendinBlueEmailNotSyncInDolNotSendinBlue = Empfängeradresse(n) Dolibarr fehlt in der SendinBlue-Liste / im Segment
```suggestion
SendinBlueEmailNotSyncInDolNotSendinBlue = Dolibarr-Empfängeradresse(n) fehlt in der SendinBlue-Liste / im Segment
```

2021-12-15 10:05 UTC, atm-florianm commented on langs/de_DE/sendinblue.lang
> +abmelden = abmelden
⚠ Übersetzungsschlüssel dürfen nicht übersetzt werden

2021-12-15 17:07 UTC, atm-florianm commented
Vielen Dank für die Übersetzung. Ich habe ein paar Änderungsvorschläge gemacht, aber wir werden das PR zusammenführen sobald die Probleme beseitigt sind.

2022-02-21 08:51 UTC, atm-john requested changes
Change request

2022-03-04 10:03 UTC, atm-john commented
Close due to no activity

2022-03-04 10:03 UTC, closed without merging